runtime: nodejs

env: flex

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 7

env_variables:
  DATABASE_HOST: cloudsql
  DATABASE_USER: root
  DATABASE_PASSWORD: password
  DATABASE_NAME: assignment4

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: fs1040-website:us-east1:fs1040db=tcp:3306
