runtime: custom

env: flex

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 7

env_variables:
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME}

includes:
  - dbconfig.yaml

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: fs1040-website:us-east1:fs1040db=tcp:3306
