version: "3.7"

services:
  api:
    # image: node:12-alpine
    build:
      context: .
      dockerfile: Dockerfile
    #command: sh -c "npm install && npm run start"
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.7
    volumes:
      - test-mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'assignment4'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # MYSQL_ROOT_PASSWORD: secret
      # MYSQL_DATABASE: main_test

volumes:
  test-mysql-data:
